import UIKit
import NimbleExtensions

/// The single policy for feedback generated by KorSign. System controls own their haptics.
enum AppHaptics {
    enum Category: String {
        case navigation = "KorSign.haptics.navigation"
        case actions = "KorSign.haptics.actions"
        case results = "KorSign.haptics.results"
    }

    static let enabledKey = "KorSign.haptics.enabled"
    private static var lastFeedback: TimeInterval = -.infinity

    static func migratePreferences(_ defaults: UserDefaults = .standard) {
        if defaults.object(forKey: Category.navigation.rawValue) == nil,
           let previous = defaults.object(forKey: "KorSign.tabBarHaptics") as? Bool {
            defaults.set(previous, forKey: Category.navigation.rawValue)
        }
        if defaults.object(forKey: Category.actions.rawValue) == nil {
            let previous = ["KorSign.libraryPlusHaptics", "KorSign.libraryEditHaptics"]
                .compactMap { defaults.object(forKey: $0) as? Bool }
            if !previous.isEmpty {
                defaults.set(previous.allSatisfy { $0 }, forKey: Category.actions.rawValue)
            }
        }
    }

    static func isEnabled(_ category: Category, defaults: UserDefaults = .standard) -> Bool {
        (defaults.object(forKey: enabledKey) as? Bool ?? true)
            && (defaults.object(forKey: category.rawValue) as? Bool ?? true)
    }

    static func action() { play(.actions) { NBHaptic.tap() } }
    static func navigation() { play(.navigation) { NBHaptic.selection() } }
    static func tabTouch() { play(.navigation) { NBHaptic.tap() } }
    static func result(_ type: UINotificationFeedbackGenerator.FeedbackType) {
        play(.results) { NBHaptic.notify(type) }
    }
    static func notice() { play(.results) { NBHaptic.tap() } }

    private static func play(_ category: Category, feedback: @escaping () -> Void) {
        // Emit inside UI actions before navigation/rendering begins. Only background
        // completions need to hop onto the main queue.
        let emit = {
            guard UIApplication.shared.applicationState == .active, isEnabled(category) else { return }
            let now = ProcessInfo.processInfo.systemUptime
            // Coalesce a button, its immediate operation, and its toast into one pulse.
            guard now - lastFeedback >= 0.1 else { return }
            lastFeedback = now
            feedback()
        }
        if Thread.isMainThread {
            emit()
        } else {
            DispatchQueue.main.async(execute: emit)
        }
    }
}
