name: Update Repository

on:
  workflow_call:
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: korsign-source-feed
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Update app-repo.json
        run: |
          ./update-repo.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update repo"
          add: app-repo.json
